spring.application.name=MoviesAndActors
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.datasource.url=jdbc:h2:mem:ActorMngmt
spring.datasource.url=jdbc:h2:file:./DB/actorsAndMovies
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

