spring:
  datasource:
    generate-unique-name: false
    url: jdbc:h2:file:./h2_file/mydb
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  config:
    activate:
      on-profile: dev
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

server:
  port: 8080

---

spring:
  datasource:
    generate-unique-name: false
    url: jdbc:h2:mem:blog
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  config:
    activate:
      on-profile: test
  sql:
    init:
      mode: always
      data-locations: classpath:dataProd.sql

server:
  port: 8090