# nome applicazione
spring.application.name=Blog

# nome datasource
spring.datasource.name=blog

# evita nomi casuali DB
spring.datasource.generate-unique-name=false

# aggiorna schema automaticamente
spring.jpa.hibernate.ddl-auto=update

# attiva profilo DEV
spring.profiles.active=dev